### ISSUE TITLE
该sdk似乎没有对飞书的重推机制进行事件去重，我好像没找到相应的代码

### ISSUE THREAD

**Issue by Justin3go** [larksuite/node-sdk#10]
我好像搜不到该群，顺便再问一个问题，该sdk似乎没有对飞书的重推机制进行事件去重，我好像没找到相应的代码

_Originally posted by @Justin3go in https://github.com/larksuite/node-sdk/issues/8#issuecomment-1257711024_

**Comment by mazhe-nerd** [comment]
https://open.feishu.cn/document/ukTMukTMukTM/uUTNz4SN1MjL1UzM#1783f79c
可以在事件处理函数中拿到event_id（2.0版本事件）或者uuid（1.0版本事件）对事件的唯一性进行检查，考虑需不需要处理该事件哈。

**Comment by mazhe-nerd** [comment]
> ```
>     我好像搜不到该群，顺便再问一个问题，该sdk似乎没有对飞书的重推机制进行事件去重，我好像没找到相应的代码
> ```
> 
> _Originally posted by @Justin3go in [#8 (comment)](https://github.com/larksuite/node-sdk/issues/8#issuecomment-1257711024)_

https://open.feishu.cn/document/ukTMukTMukTM/uUTNz4SN1MjL1UzM#1783f79c
可以在事件处理函数中拿到event_id（2.0版本事件）或者uuid（1.0版本事件）对事件的唯一性进行检查，考虑需不需要处理该事件哈。
