### ISSUE TITLE
使用sdk 时报错，某些模块 Could not resolve？

### ISSUE THREAD

**Issue by Aganivi** [larksuite/node-sdk#100]
✘ [ERROR] Could not resolve "crypto"

    node_modules/.pnpm/@larksuiteoapi+node-sdk@1.32.0/node_modules/@larksuiteoapi/node-sdk/es/index.js:15:19:
      15 │ import crypto from 'crypto';
         ╵                    ~~~~~~~~

  The package "crypto" wasn't found on the file system but is built into node.
  Add "node_compat = true" to your wrangler.toml file and make sure to prefix the module name with "node:" to enable Node.js compatibility.

✘ [ERROR] Could not resolve "fs"

    node_modules/.pnpm/@larksuiteoapi+node-sdk@1.32.0/node_modules/@larksuiteoapi/node-sdk/es/index.js:19:15:
      19 │ import fs from 'fs';
         ╵                ~~~~

  The package "fs" wasn't found on the file system but is built into node.
  Add "node_compat = true" to your wrangler.toml file and make sure to prefix the module name with "node:" to enable Node.js compatibility.

✘ [ERROR] Could not resolve "querystring"

    node_modules/.pnpm/@larksuiteoapi+node-sdk@1.32.0/node_modules/@larksuiteoapi/node-sdk/es/index.js:21:15:
      21 │ import qs from 'querystring';
         ╵                ~~~~~~~~~~~~~

  The package "querystring" wasn't found on the file system but is built into node.
  Add "node_compat = true" to your wrangler.toml file and make sure to prefix the module name with "node:" to enable Node.js compatibility.

**Comment by mazhe-nerd** [comment]
这个sdk是运行在node环境的，不能用在别的环境
