### ISSUE TITLE
1.37.0升级后接口都报错AxiosError: options must be an object

### ISSUE THREAD

**Issue by lxw15337674** [larksuite/node-sdk#107]
我从1.34.0升级后所有接口都报错，是做了什么破坏性改动吗：
![image](https://github.com/user-attachments/assets/745b7408-763e-44bb-a3c8-e4c57bce1c1e)

下面是我一个接口的代码：
```typescript
interface GetMemosDataParams {
    page_token?: string;
    filter?: Filter;
}
export const getMemosDataActions = async ({ page_token, filter }: GetMemosDataParams = {}) => {
    try {
        const data = await getRecordsActions({
            page_token,
            sort: [{
                'field_name': "created_time",
                "desc": true
            }],
            page_size: 20,
            filter
        })
        return data!
    } catch (error) {
        console.error("memos获取失败:", error);
        throw error;
    }
};
```

**Comment by mazhe-nerd** [comment]
升级到1.37.1，axios有个bug

**Comment by lxw15337674** [comment]
> 升级到1.37.1；axios 0.28.1有个bug；1.37.1避开了axios这个版本

其他接口可以了，图片这个还是不行
![image](https://github.com/user-attachments/assets/827127c2-83a4-47ca-925d-679ee0101e14)

**Comment by mazhe-nerd** [comment]
@lxw15337674 报错信息是？

**Comment by mazhe-nerd** [comment]
> > 升级到1.37.1；axios 0.28.1有个bug；1.37.1避开了axios这个版本
> 
> 其他接口可以了，图片这个还是不行 ![image](https://private-user-images.githubusercontent.com/19898669/371367241-827127c2-83a4-47ca-925d-679ee0101e14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDU4ODIsIm5iZiI6MTcyNzQwNTU4MiwicGF0aCI6Ii8xOTg5ODY2OS8zNzEzNjcyNDEtODI3MTI3YzItODNhNC00N2NhLTkyNWQtNjc5ZWUwMTAxZTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAyNTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNjNlYTkyMTg1NWE2N2M3MWJjMTgzYWVlNmMwMDRiYmRhN2FhZTk4MTQ4ZTM3OWEwMWYxMzU1ODZmZjA5ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5-qlmvSVjo7LcK6vEH77szUBgpf-CdCuEUwZwqrI4Jw)

@lxw15337674 你的file_tokens是不是传了个空数组

**Comment by lxw15337674** [comment]
> > > 升级到1.37.1；axios 0.28.1有个bug；1.37.1避开了axios这个版本
> > 
> > 
> > 其他接口可以了，图片这个还是不行 ![image](https://private-user-images.githubusercontent.com/19898669/371367241-827127c2-83a4-47ca-925d-679ee0101e14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDU4ODIsIm5iZiI6MTcyNzQwNTU4MiwicGF0aCI6Ii8xOTg5ODY2OS8zNzEzNjcyNDEtODI3MTI3YzItODNhNC00N2NhLTkyNWQtNjc5ZWUwMTAxZTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAyNTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNjNlYTkyMTg1NWE2N2M3MWJjMTgzYWVlNmMwMDRiYmRhN2FhZTk4MTQ4ZTM3OWEwMWYxMzU1ODZmZjA5ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5-qlmvSVjo7LcK6vEH77szUBgpf-CdCuEUwZwqrI4Jw)
> 
> @lxw15337674 你的file_tokens是不是传了个空数组

截图没显示出来吗，上面显示的file_tokens是有的。
![1727406928036](https://github.com/user-attachments/assets/f85fbdb3-0cc2-40aa-a2ea-7e2dacef0db7)

**Comment by mazhe-nerd** [comment]
> > > > 升级到1.37.1；axios 0.28.1有个bug；1.37.1避开了axios这个版本
> > > 
> > > 
> > > 其他接口可以了，图片这个还是不行 ![image](https://private-user-images.githubusercontent.com/19898669/371367241-827127c2-83a4-47ca-925d-679ee0101e14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDU4ODIsIm5iZiI6MTcyNzQwNTU4MiwicGF0aCI6Ii8xOTg5ODY2OS8zNzEzNjcyNDEtODI3MTI3YzItODNhNC00N2NhLTkyNWQtNjc5ZWUwMTAxZTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAyNTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNjNlYTkyMTg1NWE2N2M3MWJjMTgzYWVlNmMwMDRiYmRhN2FhZTk4MTQ4ZTM3OWEwMWYxMzU1ODZmZjA5ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5-qlmvSVjo7LcK6vEH77szUBgpf-CdCuEUwZwqrI4Jw)
> > 
> > 
> > @lxw15337674 你的file_tokens是不是传了个空数组
> 
> 截图没显示出来吗，上面显示的file_tokens是有的。 ![1727406928036](https://private-user-images.githubusercontent.com/19898669/371379007-f85fbdb3-0cc2-40aa-a2ea-7e2dacef0db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDcyNzYsIm5iZiI6MTcyNzQwNjk3NiwicGF0aCI6Ii8xOTg5ODY2OS8zNzEzNzkwMDctZjg1ZmJkYjMtMGNjMi00MGFhLWEyZWEtN2UyZGFjZWYwZGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAzMTYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzODc3NGVhYWQyOGU2NmRjNjBiMjBiNTBkN2E4NzdkZWNhNWIyODYxNzAxNjkzZDEyZDNhODRlYTRmYWM5MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j5UtAo02I0V7UR2gbVL7EnpCo1qZsym7F0FUXNgjN-E)

不好意思，没看到这里。e.response.data.error.log_id 可以给我下不？

**Comment by mazhe-nerd** [comment]
> > > > > > 升级到1.37.1；axios 0.28.1有个bug；1.37.1避开了axios这个版本
> > > > > 
> > > > > 
> > > > > 其他接口可以了，图片这个还是不行 ![image](https://private-user-images.githubusercontent.com/19898669/371367241-827127c2-83a4-47ca-925d-679ee0101e14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDU4ODIsIm5iZiI6MTcyNzQwNTU4MiwicGF0aCI6Ii8xOTg5ODY2OS8zNzEzNjcyNDEtODI3MTI3YzItODNhNC00N2NhLTkyNWQtNjc5ZWUwMTAxZTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAyNTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNjNlYTkyMTg1NWE2N2M3MWJjMTgzYWVlNmMwMDRiYmRhN2FhZTk4MTQ4ZTM3OWEwMWYxMzU1ODZmZjA5ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5-qlmvSVjo7LcK6vEH77szUBgpf-CdCuEUwZwqrI4Jw)
> > > > 
> > > > 
> > > > @lxw15337674 你的file_tokens是不是传了个空数组
> > > 
> > > 
> > > 截图没显示出来吗，上面显示的file_tokens是有的。 ![1727406928036](https://private-user-images.githubusercontent.com/19898669/371379007-f85fbdb3-0cc2-40aa-a2ea-7e2dacef0db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDcyNzYsIm5iZiI6MTcyNzQwNjk3NiwicGF0aCI6Ii8xOTg5ODY2OS8zNzEzNzkwMDctZjg1ZmJkYjMtMGNjMi00MGFhLWEyZWEtN2UyZGFjZWYwZGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAzMTYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzODc3NGVhYWQyOGU2NmRjNjBiMjBiNTBkN2E4NzdkZWNhNWIyODYxNzAxNjkzZDEyZDNhODRlYTRmYWM5MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j5UtAo02I0V7UR2gbVL7EnpCo1qZsym7F0FUXNgjN-E)
> > 
> > 
> > 不好意思，没看到这里。e.response.data.error.log_id 可以给我下不？
> 
> '20240927151746C33CD2C472471369B023'
> 
> ![image](https://private-user-images.githubusercontent.com/19898669/371433480-d2795bbd-b4fd-45c3-95a6-51ccedc29963.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MjE4NTMsIm5iZiI6MTcyNzQyMTU1MywicGF0aCI6Ii8xOTg5ODY2OS8zNzE0MzM0ODAtZDI3OTViYmQtYjRmZC00NWMzLTk1YTYtNTFjY2VkYzI5OTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA3MTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NzczMTcyMjNjNjE2ZGE4ODZiMGZmYWI1NWJjNjY0NzZkN2Y3ZDE1MWFkNTlhYjZhMGJlY2RlOGYzMGQxZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lPOpzd6mehGUZHjBPZoxJhh2CSI_T8Vi2Uw5561CgXw)

现在可以了嘛？如果还不行的话，麻烦请求头带个x-tt-trace: 1，然后在给我下log-id哈

**Comment by mazhe-nerd** [comment]
@lxw15337674 错误原因是file_tokens被转换成了file_tokens[]=xxx&file_tokens[]=xxx这种类型的query参数（对应下图方式4，应该没有[]），导致报错。
![img_v3_02f6_efbbc64c-88c3-4eb9-95ad-86fdf560096g](https://github.com/user-attachments/assets/5d354dc8-0401-41af-919b-0a53121841bf)
我本地验证转换是方式一，调用正常：
![image](https://github.com/user-attachments/assets/59a804ab-89e0-4f9b-be07-41ffcdda3c41)

排查思路：
1. 看一下报错的接口，是否转换成了file_tokens[]=xxx&file_tokens[]=xxx这种类型
2. 如果是的话，查看一下是否有自定义httpInstance或者interceptors，把这个转换给改掉了
3. 如果不是2的话，可以看一下项目中实际安装的qs版本，sdk内部使用的是 `qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'repeat' })`，做转换，应该会转换为方式一：
![image](https://github.com/user-attachments/assets/c69a5e5f-c367-40d9-9eac-f3f3b1fb1045)
sdk内部的转换代码：
![image](https://github.com/user-attachments/assets/e72e8b2a-ba41-47b6-b394-06feb068fa5e)

**Comment by lxw15337674** [comment]
@mazhe-nerd  确实是转换的不对，但我看pnpm-lock和npm包源码都是对的，你看下截图
![image](https://github.com/user-attachments/assets/7c1adec2-fc30-47ca-bd90-d0f6d392f6ca)

![02c4ff4fe9870e01288087d1a833310](https://github.com/user-attachments/assets/0b9746b1-cade-4e0f-b833-421c9eb0e967)

![image](https://github.com/user-attachments/assets/1f6faa2c-d9f2-4af1-81ea-e4fde19a9346)

**Comment by mazhe-nerd** [comment]
@lxw15337674 查到原因了，axios的0.28.0版本有问题，会将repeat转为brackets，可以锁一下axios版本到0.27.2

**Comment by lxw15337674** [comment]
> @lxw15337674 查到原因了，axios的0.28.0版本有问题，会将repeat转为brackets，可以锁一下axios版本到0.27.2

要不有空更新到最新版本吧，现在axios不都1.x了吗？现在真是各种坑。。。

**Comment by mazhe-nerd** [comment]
> > @lxw15337674 查到原因了，axios的0.28.0版本有问题，会将repeat转为brackets，可以锁一下axios版本到0.27.2
> 
> 要不有空更新到最新版本吧，现在axios不都1.x了吗？现在真是各种坑。。。

嗯，0.27.2比较稳定；1.x之前尝试升了一下，break change挺多的，需要全面回归一下

**Comment by lxw15337674** [comment]
> > > @lxw15337674 查到原因了，axios的0.28.0版本有问题，会将repeat转为brackets，可以锁一下axios版本到0.27.2
> > 
> > 
> > 要不有空更新到最新版本吧，现在axios不都1.x了吗？现在真是各种坑。。。
> 
> 嗯，0.27.2比较稳定；1.x之前尝试升了一下，break change挺多的，需要全面回归一下

那等你再发个包吧？不行可以加点单测😄

**Comment by mazhe-nerd** [comment]
> > > > @lxw15337674 查到原因了，axios的0.28.0版本有问题，会将repeat转为brackets，可以锁一下axios版本到0.27.2
> > > 
> > > 
> > > 要不有空更新到最新版本吧，现在axios不都1.x了吗？现在真是各种坑。。。
> > 
> > 
> > 嗯，0.27.2比较稳定；1.x之前尝试升了一下，break change挺多的，需要全面回归一下
> 
> 那等你再发个包吧？不行可以加点单测😄

OK，可以先用resolutions验证下不： 
`  "resolutions": {
    "axios": "0.27.2"
  }
  没问题的话我发个包

**Comment by lxw15337674** [comment]
> > > > > @lxw15337674 查到原因了，axios的0.28.0版本有问题，会将repeat转为brackets，可以锁一下axios版本到0.27.2
> > > > 
> > > > 
> > > > 要不有空更新到最新版本吧，现在axios不都1.x了吗？现在真是各种坑。。。
> > > 
> > > 
> > > 嗯，0.27.2比较稳定；1.x之前尝试升了一下，break change挺多的，需要全面回归一下
> > 
> > 
> > 那等你再发个包吧？不行可以加点单测😄
> 
> OK，可以先用resolutions验证下不： `"resolutions": {"axios": "0.27.2"}` 没问题的话我发个包

我试了，可以的
