### ISSUE TITLE
有漏洞

### ISSUE THREAD

**Issue by zhouyuxiang0** [larksuite/node-sdk#112]
<img width="582" alt="image" src="https://github.com/user-attachments/assets/e41d7fe3-b869-413b-8f3c-cb8a0c0b45fe">

**Comment by zhouyuxiang0** [comment]
一直想用这库，这问题一直没见有解决。。。

**Comment by mazhe-nerd** [comment]
GET，我修复一下，下个版本fix，感谢同学

**Comment by mazhe-nerd** [comment]
1.40.1已修复；移除了对lodash.pick的依赖
