### ISSUE TITLE
client.im.message.updateByCard 调用报错 230001 Your request contains an invalid request parameter, ext=invalid msg_type.

### ISSUE THREAD

**Issue by Sleaf** [larksuite/node-sdk#115]
请求 data:

{"msg_type":"interactive","content":"{\"type\":\"template\",\"data\":{\"template_id\":\"xxx\",\"template_variable\":{\"action\":\"skip\"}}}"}

🤔看[原始文档](https://open.feishu.cn/document/server-docs/im-v1/message/update?appId=cli_a7c736cfe43d100e) msg_type 不支持 interactive？是哪一环没有更新

**Comment by Sleaf** [comment]
https://open.feishu.cn/document/server-docs/im-v1/message-card/patch
是不是应该调用 patch 方法？
![image](https://github.com/user-attachments/assets/62f3e98c-2c16-4672-abf1-604cad7a999a)

**Comment by Sleaf** [comment]
翻了下  用client.im.message.patch 就行了
建议更新一下文档

**Comment by mazhe-nerd** [comment]
对，updateByCard是update的语法糖，之前支持更新卡片，后来拆分到patch了
