### ISSUE TITLE
搜索云文档这个接口没看到node.js版本的调用示例，飞书机器人给的也不对

### ISSUE THREAD

**Issue by fat-fat-gold** [larksuite/node-sdk#116]
![image](https://github.com/user-attachments/assets/e21c5d59-0422-427e-8c96-6ad445b2d686)

**Comment by mazhe-nerd** [comment]
这个接口目前还不支持语义化调用，先用普通调用的方式哈：https://github.com/larksuite/node-sdk/blob/main/README.zh.md#%E6%99%AE%E9%80%9A%E8%B0%83%E7%94%A8
