### ISSUE TITLE
事件订阅node版本无法触发

### ISSUE THREAD

**Issue by BinGuo666** [larksuite/node-sdk#12]
![image](https://user-images.githubusercontent.com/32035465/197748860-57420915-cab7-4ef9-a0bb-7ba9213913d9.png)

**Comment by BinGuo666** [comment]
机器人的权限和网络都配置好了，没办法监听到相应的事件

**Comment by mazhe-nerd** [comment]
> 机器人的权限和网络都配置好了，没办法监听到相应的事件

在开放平台配置了事件触发网址了没？可以先跟着这个文档一步一步实现下哈：https://github.com/larksuite/node-sdk/issues/12#issuecomment-1290321914
