### ISSUE TITLE
源码是否实时更新同步

### ISSUE THREAD

**Issue by huixisheng** [larksuite/node-sdk#13]
https://www.npmjs.com/package/@larksuiteoapi/node-sdk/v/1.5.0  npmjs.com 发布了1.5.0 版本
https://github.com/larksuite/node-sdk/blob/main/package.json#L3  main 分支是1.0.3

**Comment by mazhe-nerd** [comment]
> https://www.npmjs.com/package/@larksuiteoapi/node-sdk/v/1.5.0 npmjs.com 发布了1.5.0 版本 https://github.com/larksuite/node-sdk/blob/main/package.json#L3 main 分支是1.0.3

你好同学，源码是实时更新的哈。
我们内部有一套工具链，会基于这份源码变更来进行build和版本计算，完毕后将结果发到npm，源码中package.json的version没有同步修改，我下次发布的时候把同步修改也加进去哈。

**Comment by mazhe-nerd** [comment]
已同步
