### ISSUE TITLE
支持的openapi范围咨询

### ISSUE THREAD

**Issue by yayayahei** [larksuite/node-sdk#15]
看起来目前没有支持全量的接口，比如招聘下面只有两个：获取职位详情、获取招聘人员。

- 但实际上有更多：新建职位等。为什么没有支持呢？
- 灰度的接口会支持吗？比如获取职位列表？

**Comment by mazhe-nerd** [comment]
> 看起来目前没有支持全量的接口，比如招聘下面只有两个：获取职位详情、获取招聘人员。
> 
> * 但实际上有更多：新建职位等。为什么没有支持呢？
> * 灰度的接口会支持吗？比如获取职位列表？

同学你好：
1. 我们的目标是支持全量的api，但由于历史原因，一些接口沿用了旧的结构规范，这部分需要进行迁移才能被支持，目前这件事情已经在推进中了；每双周我们会更新支持的api，会升级一个中版本进行体现。这段时期只能通过request方法来手动发起调用。
2. 灰度接口不会支持。
