### ISSUE TITLE
消息推送,怎么指定url呢, 希望能指点

### ISSUE THREAD

**Issue by lybWeb2020** [larksuite/node-sdk#17]
![image](https://user-images.githubusercontent.com/75764790/204262284-cbe124f0-1f6c-4f90-893b-62dee773ee2b.png)

**Comment by mazhe-nerd** [comment]
语义化调用就好哈，不需要指定url：https://github.com/larksuite/node-sdk/blob/main/README.zh.md#api%E8%B0%83%E7%94%A8
