### ISSUE TITLE
参数格式问题

### ISSUE THREAD

**Issue by ZJH9Rondo** [larksuite/node-sdk#2]
client.im.message.create 里面 data 的 content 参数格式必须是个 JSON.String 格式才可以，另外，如果要在 BOE 环境测试，要设置 初始化 Client 的时候，把 domain 切到 BOE 。这文档里写的操作说明太少了，不靠谱，至少应该找个新人按照这个跑一遍看下缺啥再补全了放出来。

**Comment by mazhe-nerd** [comment]
收到，如果是字节的同学，可以飞书call下我：马哲，我拉你进内部使用群。
第一个问题：SDK里的参数类型是按照开放平台提供的api文档来的，编码是SDK的提示应该是一个string，这块开放平台的文档里有说明：https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/im-v1/message/create_json，如果还是比较难理解我这边可以反馈一下完善一下开放平台的文档哈。
第二个问题：这块文档里确实没有显式的表明，下个版本我们加一下哈。

**Comment by mazhe-nerd** [comment]
已解决

**Comment by mazhe-nerd** [comment]
已解决
