### ISSUE TITLE
企业自建应用是否封装 tenant_access_token 的获取？

### ISSUE THREAD

**Issue by shenshen0318** [larksuite/node-sdk#22]
以前的 SDK 封装了 app_access_token、tenant_access_token 的获取，这个 SDK 是否有封装？

**Comment by mazhe-nerd** [comment]
tenant_access_token的获取已经封装了；app_access_token需要开发者手动指定

**Comment by shenshen0318** [comment]
但是在使用发消息的接口时，会显示 tenant_access_token 为 undefined，我们就又请求了一遍 tenant_access_token

**Comment by mazhe-nerd** [comment]
可以写一个出问题的demo代码嘛？我这边debug看下
