### ISSUE TITLE
请问sdk如何获取JSAPI 临时授权凭证？

### ISSUE THREAD

**Issue by kilik52** [larksuite/node-sdk#29]
你好，请问这个sdk有jssdk方面的api吗？

比如👇这个：

https://open.feishu.cn/open-apis/jssdk/ticket/get

或者有没有直接能够通过url生成一个h5 js需要的config的接口？

**Comment by mazhe-nerd** [comment]
没有哈，这个sdk只是针对服务端的open-api的
