### ISSUE TITLE
drive.file.bitable_record_changed_v1平台有这个事件的文档，但是库里没有这个事件，修改原代码，是可以获取到这个事件响应的数据的

### ISSUE THREAD

**Issue by xlz-324** [larksuite/node-sdk#31]
[https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/event/list/bitable-record-changed](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/event/list/bitable-record-changed)

**Comment by xlz-324** [comment]
![image](https://user-images.githubusercontent.com/77909655/218654037-2f95cc48-09dd-4238-a00d-629924c518f6.png)
这个事件是开放了的

**Comment by mazhe-nerd** [comment]
SDK会拉开放平台的文档生成可执行的代码/类型定义，由于有一些老版本的文档无法解析，所以这部分没有纳入SDK里；我们会不定期手动补齐这些内容，这期间使用是没问题的，只不过会有类型上的错误提示，ignore掉就好了。
