### ISSUE TITLE
文件巨大，VS Code 基本无法打开

### ISSUE THREAD

**Issue by SeongBrave** [larksuite/node-sdk#35]
![image](https://user-images.githubusercontent.com/10784393/221331334-ccefef36-45e8-4747-bea6-c5804876b1c8.png)
😱 这真是官方的吗？这就是所谓字节技术？无法查看api，打开 编辑器直接崩掉

**Comment by mazhe-nerd** [comment]
你好同学，这个可以指向前期设计时的问题：是提供一个包含所有开放api和事件的sdk还是提供一个可以依开发者自身业务场景来按需引入所需开放api和事件的sdk。前者比较便利但问题在于包体积比较大，后者需要在编码时多做一层引入的心智判断，但优点在于包体积比较小。因为这个sdk是跑在服务端的，所以包体积相交来说不那么重要，因此我们将所有api和事件都进行了归一化处理，包括types，es和lib，都只有一个文件，也就是现在的样子。

不过随着开放出来的api和事件越来越多，归一化后的单个文件会越来越大，确实会造成问题，我们也在考虑按project的维度进行拆分，每一个文件只包括project本身所属的内容，这样也有利于未来做场景化的封装（如有的话）。

最后，可以提供一下vscode的版本吗？我这边排查下。现在的量应该还没到无法编辑查看的程度。
