### ISSUE TITLE
多维表格新建数据表报400

### ISSUE THREAD

**Issue by even0318** [larksuite/node-sdk#36]
只要把类型17那个field注释掉就能创建成功，不然就会报400，code是99992402
`const res = await this.larkClient.bitable.appTable.create({
      path: {
        app_token: body.app_token,
      },
      data: {
        table: {
          name: `结果 - ${new Date().valueOf()}`,
          fields: [
            {
              field_name: '接口',
              type: 1,
            },
            {
              field_name: '影响程度',
              property: {
                options: [
                  {
                    color: 0,
                    name: 'P0',
                  },
                  {
                    color: 1,
                    name: 'P1',
                  },
                  {
                    color: 2,
                    name: 'P2',
                  },
                ],
              },
              type: 3,
            },
            {
              field_name: '修复优先级',
              property: {
                options: [
                  {
                    color: 0,
                    name: 'P0',
                  },
                  {
                    color: 1,
                    name: 'P1',
                  },
                  {
                    color: 2,
                    name: 'P2',
                  },
                ],
              },
              type: 3,
            },
            {
              field_name: '结果',
              property: {
                options: [
                  {
                    color: 36,
                    name: '通过',
                  },
                  {
                    color: 22,
                    name: '失败',
                  },
                  {
                    color: 0,
                    name: '无效',
                  },
                ],
              },
              type: 3,
            },
            // {
            //   field_name: '截图',
            //   type: 17,
            // },
            {
              field_name: '备注',
              type: 1,
            },
            {
              field_name: '场景',
              property: {
                options: [],
              },
              type: 3,
            },
            {
              field_name: '链接',
              type: 15,
            },
          ],
        },
      },
    });`

**Comment by zmzimpl** [comment]
所以是怎么解决的？碰上了同样的问题，type: 17 会报错
