### ISSUE TITLE
获取机器人信息相关接口

### ISSUE THREAD

**Issue by shfshanyue** [larksuite/node-sdk#41]
在文档中有机器人相关接口 https://open.feishu.cn/document/ukTMukTMukTM/uAjMxEjLwITMx4CMyETM ，但是在 sdk 中并没有，是否可以更新一下。

我看到 sdk 大多数是根据 code-gen 生成的，但是并没有看到 code gen 生成的具体代码逻辑，这里能够开放一下方便提交 pr 吗

**Comment by mazhe-nerd** [comment]
sdk会根据开放平台的文档数据来生成语义化的调用方式，但一些api的结构目前无法用来生成，这部分我们在推进进行整改了。在此期间可以通过[普通调用](https://github.com/larksuite/node-sdk/blob/main/README.zh.md#%E6%99%AE%E9%80%9A%E8%B0%83%E7%94%A8)的方式来进行调用。code-gen的代码目前没有开源，这部分逻辑会在定期升级sdk的语义化调用代码时用到。

**Comment by shfshanyue** [comment]
> sdk会根据开放平台的文档数据来生成语义化的调用方式，但一些api的结构目前无法用来生成，这部分我们在推进进行整改了。在此期间可以通过[普通调用](https://github.com/larksuite/node-sdk/blob/main/README.zh.md#%E6%99%AE%E9%80%9A%E8%B0%83%E7%94%A8)的方式来进行调用。code-gen的代码目前没有开源，这部分逻辑会在定期升级sdk的语义化调用代码时用到。

可以的，我使用了普通调用，也很好用
