### ISSUE TITLE
如何语义化获取接口

### ISSUE THREAD

**Issue by RidiculousDoge** [larksuite/node-sdk#42]
我查阅了飞书开发者文档和README，但不清楚如何获取接口。业务域.资源.方法，有与飞书文档的对应关系吗？例如发送消息接口。

**Comment by mazhe-nerd** [comment]
可以打开api调试台，根据url上的字段拼接project.resource.apiName：
![image](https://user-images.githubusercontent.com/106217973/230263988-7f3657a6-6201-4cab-b61d-92071b33c178.png)

**Comment by RidiculousDoge** [comment]
Thanks!
