### ISSUE TITLE
为什么飞书会回复多次呢？

### ISSUE THREAD

**Issue by fu1996** [larksuite/node-sdk#43]
![image](https://user-images.githubusercontent.com/42232973/230708289-795ff44e-6832-4761-bc0c-0c35e5dbf793.png)

我按照readme.md 里的方式进行编写的，现在不知道是哪里出现了问题。无论是本地还是线上，飞书都会推送多次。导致重复回复

**Comment by mazhe-nerd** [comment]
看起来是没有及时响应飞书的推送，可以看下这里的描述：https://open.feishu.cn/document/ukTMukTMukTM/uYDNxYjL2QTM24iN0EjN/event-subscription-configure-/encrypt-key-encryption-configuration-case#9cd4c9b1

**Comment by fu1996** [comment]
> 看起来是没有及时响应飞书的推送，可以看下这里的描述：https://open.feishu.cn/document/ukTMukTMukTM/uYDNxYjL2QTM24iN0EjN/event-subscription-configure-/encrypt-key-encryption-configuration-case#9cd4c9b1

感谢解答。
我还有如下疑问：飞书重试以后如果返回了200的状态吗？此条消息不会在进行重试了吧？

**Comment by fu1996** [comment]
![image](https://user-images.githubusercontent.com/42232973/230760172-ba6ab1b2-5c49-4972-8352-7c8a5523c555.png)
关于疑问3 我当前的做法是飞书 如果有重试的数据，我就直接return处理了，不知道飞书是否会对此条数据进行下次重试呢？还是标记为完成呢？

**Comment by mazhe-nerd** [comment]
问题1和问题3：只要给飞书的请求一个响应即可，响应内容不重要，飞书收到后就不会继续推送了。
问题2：目前应该是看不到的，我要在确定下

**Comment by fu1996** [comment]
> 问题1和问题3：只要给飞书的请求一个响应即可，响应内容不重要，飞书收到后就不会继续推送了。 问题2：目前应该是看不到的，我要在确定下，可以在业务侧手动维护一下状态

我怎么去构造一个响应呢？我的目的是飞书不再继续推送，并且这个响应不会发送给信息发送人。
![image](https://user-images.githubusercontent.com/42232973/230780452-433d3fb7-6d21-4cd8-bcdd-647068409fac.png)
通过源码分析是，只要返回给飞书一个 {"code":0} 的对象就代表响应成功了吗？因为现在看不了那些是在重试队列中，所以有些难以判断此方法是否有效

**Comment by mazhe-nerd** [comment]
> 我怎么去构造一个响应呢？我的目的是飞书不再继续推送，并且这个响应不会发送给信息发送人。 ![image](https://user-images.githubusercontent.com/42232973/230780452-433d3fb7-6d21-4cd8-bcdd-647068409fac.png) 通过源码分析是，只要返回给飞书一个 {"code":0} 的对象就代表响应成功了吗？因为现在看不了那些是在重试队列中，所以有些难以判断此方法是否有效

飞书的推送是针对事件而言的，响应这个事件只要给他回复一个status为200的http即可。上面这个截图看起来是一个api的调用，推送和这个无关。

咋们对齐一下这个问题：在代码中，注册了im.message.receive_v1事件来接收飞书推送的消息事件，拿到事件后，调用im.create方法来回复消息，现在消息会回复多次，不符合预期。

问题原因：由于没有给im.message.receive_v1一个返回，所以飞书认为这个消息推送失败了，详见[文档](https://open.feishu.cn/document/ukTMukTMukTM/uYDNxYjL2QTM24iN0EjN/event-subscription-configure-/encrypt-key-encryption-configuration-case#9cd4c9b1)，因此会重新推送，继而又触发这个注册了的响应函数，其中调用im.create方法来回复消息，表现上就是消息会回复多次。

解决方案：给im.message.receive_v1事件一个返回即可。可以抓包看看响应是否发送。

**Comment by jokingzhang** [comment]
使用koa-router 官方的适配器，没有返回200状态码，应该怎么解决？

**Comment by mazhe-nerd** [comment]
可能有2个原因：
1. 注册的事件处理函数运行出错或者超时
2. 使用的中间件运行有报错或者超时
建议看一下日志，debugger下代码
