### ISSUE TITLE
云空间文件上传api返回未知错误

### ISSUE THREAD

**Issue by didnhdj** [larksuite/node-sdk#45]
接口：https://open.feishu.cn/open-apis/drive/v1/files/upload_all

请求体：{
file：fs.createReadStream(filePath),
file_name:'linux.png',
parent_node:'doxcnKaRoFFyXR0F0vitI6fCfixxxxx',
parent_type:"explorer",
size:9268
}

返回：{
    "code": 1061001,
    "msg": "unknown error.",
    "error": {
        "log_id": "202304162015407FE8A9174362798A6D6B"
    }
}
## sdk 和api调试台均是相同结果

**Comment by mazhe-nerd** [comment]
同学你好，具体业务api的请求错误，可以提交下技术支持哈：https://open.feishu.cn
![image](https://user-images.githubusercontent.com/106217973/232374118-6a30b1d2-d1ee-44fc-8719-55f1e63d5153.png)
