### ISSUE TITLE
有无 oapi-node-sdk 飞书讨论群

### ISSUE THREAD

**Issue by UNICKCHENG** [larksuite/node-sdk#47]
在之前的 issues 中有提到这个飞书内部群，不知道现在是否开放，如果开放了，求拉，感谢🙏

**Comment by mazhe-nerd** [comment]
你好同学，目前还没有对外的node飞书讨论群，现阶段还是期望大家可以利用github的issue的机制来讨论问题。现在有一个飞书开发者互助交流的大群，如果有帮助可以加一下：https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=94cid737-e820-417b-9b42-dbce785fdd09
