### ISSUE TITLE
请问如何调试这个项目

### ISSUE THREAD

**Issue by stonyz** [larksuite/node-sdk#5]
初学者，想请通过这个项目学习typescript. 请问如何入手？
VS Code 打开了，却不知如何下手。还请不吝赐教！

**Comment by mazhe-nerd** [comment]
> 初学者，想请通过这个项目学习typescript. 请问如何入手？ VS Code 打开了，却不知如何下手。还请不吝赐教！

你好同学，typescript官方文档是很不错的学习资料，可以看看哈：https://www.typescriptlang.org/docs/

**Comment by mazhe-nerd** [comment]
已解决
