### ISSUE TITLE
表格缺少必要的 api

### ISSUE THREAD

**Issue by anthhub** [larksuite/node-sdk#53]
https://open.feishu.cn/open-apis/sheets/v2/spreadsheets/:spreadsheetToken/values  这个 api nodejs sdk 没有

**Comment by mazhe-nerd** [comment]
一些早期的api没法进行语义化转换，sdk里没有的api只能手动用client.request来调用了

**Comment by mazhe-nerd** [comment]
可以手动调用：https://github.com/larksuite/node-sdk/blob/main/README.zh.md#%E6%99%AE%E9%80%9A%E8%B0%83%E7%94%A8
