### ISSUE TITLE
建议把调试台获取语义化方法的方式写到readme里面，文档里面写的太简略找了半天。

### ISSUE THREAD

**Issue by CodyBytedance** [larksuite/node-sdk#54]

**Comment by mazhe-nerd** [comment]
OK，文档已加：https://github.com/larksuite/node-sdk/blob/main/README.zh.md#:~:text=%E8%BF%9B%E8%A1%8C%E8%B0%83%E8%AF%95%EF%BC%9A-,%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96%E8%AF%AD%E4%B9%89%E5%8C%96%E8%B0%83%E7%94%A8%E6%8E%A5%E5%8F%A3,-%EF%BC%9A%E7%82%B9%E5%87%BB
相关issue已pin
