### ISSUE TITLE
CardActionHandler register 为私有，外部无法注册

### ISSUE THREAD

**Issue by huixisheng** [larksuite/node-sdk#57]
https://github.com/larksuite/node-sdk/blob/1b2f108d5768ac081b3a79d1e07d7afc3d4d2e7b/dispatcher/card.ts#L75

**Comment by mazhe-nerd** [comment]
从业务视角来说，消息卡片的dispatcher只需要接收处理用户操作的cardHandler即可，因此只对外暴露了这个接口，需要用到register注册其它内容的原因是？
