### ISSUE TITLE
本地调用sdk，更新多维表格数据。返回：Code :91403

### ISSUE THREAD

**Issue by ff605732747** [larksuite/node-sdk#58]
网页在线调试中，可以更新对应多维表格数据。但本地代码调用API，返回Code :91403
经测试：网页在线调试里把tenant_access_token 换成代码请求的tenant_access_token ，返回值为 Code :91403
看上去应该是token被缓存了？没有及时更新导致鉴权失败。配置disableTokenCache：true。也没有起到作用。
求解何解决？

**Comment by ff605732747** [comment]
补充：能client.bitable.appTableRecord.list 读取。 但 client.bitable.appTableRecord.batchUpdate无法更新。

**Comment by ff605732747** [comment]
解决了

**Comment by iBoker** [comment]
> 解决了

咋解决的

**Comment by zhgqthomas** [comment]
同样遇到了这个问题 怎么解决的啊？
