### ISSUE TITLE
通讯录中批量获取用户这个方法在SDK中不存在

### ISSUE THREAD

**Issue by fanVeblen** [larksuite/node-sdk#63]
通讯录中批量获取用户信息client.contact.user.batch这个方法在SDK中不存在，但是在官方演示和代码demo中又存在，存在批量调用的场景就只能循环调用查询单个用户的接口

**Comment by mazhe-nerd** [comment]
之前openapi没有多版本的概念，project.resource.method即contact.user.batch可以唯一确定一个api，某个时间点做了一些break change，有了多版本的概念，project、resource、method不能唯一确定一个api，需要在加上version的维度，目前sdk还未支持多版本，因此会有问题。

支持多版本的代码已经写完，内部review中，**预计下个包将支持**，发布后我close这个issue。

目前可以先用request方法调用这个batch接口，避免手动循环调用的繁琐。

**Comment by mazhe-nerd** [comment]
升级到1.22.0版本，然后调用client.contact.v3.user.batch即可
