### ISSUE TITLE
approval 事件订阅缺失

### ISSUE THREAD

**Issue by lwvvvvv** [larksuite/node-sdk#64]
按照[官方文档：基于审批实现自动考勤管理](https://open.feishu.cn/document/home/automatic-attendance-management-based-on-approval/step-3-start-the-local-service) 中的示例代码
存在以下代码：
```typescript
  const eventDispatcher = new EventDispatcher({}).register({
    // 给机器人发消息、群里@机器人时将会调用此函数
    'im.message.receive_v1': async (data) => {
      const { sender, message } = data;
      const { message_type, content } = message;
...
    // 审批通过的回调
    approval: (data) => {
      // 只关注 用户配置的approvalCode 审批通过
      if (data.definition_code === approvalCode) {
        // 根据实例写入考勤、写入日程
        createLeavesByApprovalInstance(client, data.instance_code);
      }
      return 'ok';
    },
  });
```
[示例代码.zip](https://github.com/larksuite/node-sdk/files/13184787/aec25f4d5abc4ae8e4585ceec5ddfe1b_9wnZ4KYGj8.zip) 其中的index.js

但`approval`关键词在最新版sdk中并不存在，编译也会报错
<img width="1444" alt="image" src="https://github.com/larksuite/node-sdk/assets/30866542/ead4c43f-8308-4d3d-aab7-eb23bcdd115e">

SDK版本：`"@larksuiteoapi/node-sdk": "^1.21.0"`

**Comment by mazhe-nerd** [comment]
approval相关定义由于文档比较老，sdk没法生成出来，先ignore掉就行，不影响使用。
示例代码是js不会报类型错误。

**Comment by lwvvvvv** [comment]
引入后，提示 no approval-instance handler 什么的，请问是有标准的写法吗

**Comment by mazhe-nerd** [comment]
在上面写一行注释：
// @ts-ingore
