### ISSUE TITLE
Can not upload files

### ISSUE THREAD

**Issue by brennan992k** [larksuite/node-sdk#65]
this.larkClient.drive.file.uploadAll(
        {
          data: {
            file_name: '--', /// your file name
            parent_node: '--', /// your parent node
            parent_type: 'explorer',
            size: file.buffer,
            file: file.buffer,
          },
        },
        {
          headers: {
            Authorization: `Bearer ${your enant_access_token}`,
            ...new FormData().getHeaders(),
          },
        },

 **_=> throw error [error]: [
  [
    {
      message: 'Request failed with status code 400',
      config: [Object],
      request: [Object],
      response: [Object]
    },
    { code: 1061002, msg: 'params error.', error: [Object] }
  ]
]_**

**Comment by mazhe-nerd** [comment]
用的gulux吗？

**Comment by brennan992k** [comment]
I was using in NestJS. What is gulux? Is it library?

**Comment by mazhe-nerd** [comment]
可以将file的类型变为stream试试看。

buffer转stream
```
let Duplex = require('stream').Duplex;
 
function bufferToStream(buffer) {  
  let stream = new Duplex();
  stream.push(buffer);
  stream.push(null);
  return stream;
}
```

**Comment by brennan992k** [comment]
file: 
<img width="818" alt="Screenshot 2023-11-08 at 13 50 36" src="https://github.com/larksuite/node-sdk/assets/88129967/0715a236-6e5c-41b5-9ca2-4fa74dec40c4">
Not working, i convert Duplex to ReadStream right?

**Comment by mazhe-nerd** [comment]
我尝试了一下是可以的，可以用这段代码试试？
![image](https://github.com/larksuite/node-sdk/assets/106217973/9b40b99a-ef40-4680-812a-ff801940c212)
