### ISSUE TITLE
审批实例状态变更 这个事件可以用EventDispatcher来进行处理吗

### ISSUE THREAD

**Issue by cjz-lxg** [larksuite/node-sdk#68]
如题， 我配置了当审批实例状态变化时发给我指定服务器状态改变的消息，但是我发现文档中并没有给出这样的操作，我应该怎么去接受处理这个事件利用你们的sdk？下面是我做出的尝试
private initEventDispatcher() {
    this.eventDispatcher.register({
      "approval_instance": async (data: any) => {
        console.log(data);
        return "success";
      }
    } as lark.EventHandles)
  }
但是仍然会出现这样的问题
[warn]: [ 'no approval_instance handle' ]

**Comment by mazhe-nerd** [comment]
所有事件都可以通过EventDispatcher来进行注册处理。
是不是在注册代码执行前，飞书开放平台推送了这个事件，导致出现了warn。
