### ISSUE TITLE
下载文件能否支持直接导出流？

### ISSUE THREAD

**Issue by xmsz-stu** [larksuite/node-sdk#72]
背景
- 我要把导出的文件上传到别的地方
- 现在导出必须先保存到本地，然后再读取，再上传，有点麻烦

需求
- 能不能支持直接暴露文件流，我们自己控制？

**Comment by mazhe-nerd** [comment]
可以的同学，我加一下；这期间可以先用request手动调用哈

**Comment by mazhe-nerd** [comment]
这个支持了哈，升级到1.35.0可用，期间没有break change
![img_v3_02f0_b9b5aea4-1b3c-4971-9bfe-a7bf80c1d84g](https://github.com/user-attachments/assets/a43bda98-eb7e-4e54-af0d-22c3e5748628)
