### ISSUE TITLE
BUG：多维表格添加记录无法记录字段内容

### ISSUE THREAD

**Issue by absir1949** [larksuite/node-sdk#78]
使用如下方式提交记录，发现提交会返回成功，记录也会添加，但提交的字段内容为空，使用curl则正常！

`client.bitable.appTableRecord.create({
		path: {
			app_token: 'app_token',
			table_id: 'table_id',
		},
		data: {
			fields: new Map([
				['name', '111111111'],
			]),
		},
	},
).then(res => {
	console.log(res);
});`

`提交返回如下`

`{
  code: 0,
  data: {
    record: { fields: {}, id: 'recu7InJ53p5x2', record_id: 'recu7InJ53p5x2' }`

**Comment by mazhe-nerd** [comment]
把fields换成object的类型试试？目前Map的数据结构有问题
