### ISSUE TITLE
新卡片回传交互结构类型不支持

### ISSUE THREAD

**Issue by huixisheng** [larksuite/node-sdk#79]
https://open.feishu.cn/document/uAjLw4CM/ukzMukzMukzM/feishu-cards/card-callback-communication

**Comment by mazhe-nerd** [comment]
目前消息卡片的类型是手写的，没法自动生成，可以先手写一下。我看看有没有好的自动生成方式

**Comment by mazhe-nerd** [comment]
如果是验签不通的话，可以升级到1.27.0，兼容了新版卡片的验签逻辑
