### ISSUE TITLE
我要在事件处理中使用service的方法，有办法在controller里注册事件吗，不然好像拿不到ctx对象

### ISSUE THREAD

**Issue by Justin3go** [larksuite/node-sdk#8]

**Comment by Justin3go** [comment]
> > _No description provided._
> 
> 你好同学，可以补充下语境嘛？这里的service，controller和ctx指的是？

感谢你的关注，使用的是gulu框架

**Comment by mazhe-nerd** [comment]
> 

字节的同学嘛？可以飞书加入【新版oapi-nodejs-sdk灰度使用讨论群】，在群里交流哈

**Comment by mazhe-nerd** [comment]
> > > _No description provided._
> > 
> > 
> > 你好同学，可以补充下语境嘛？这里的service，controller和ctx指的是？
> 
> 感谢你的关注，使用的是gulu框架

字节的同学嘛？可以飞书加入【新版oapi-nodejs-sdk灰度使用讨论群】，在群里交流哈

**Comment by Justin3go** [comment]
我好像搜不到该群，顺便再问一个问题，该sdk似乎没有对飞书的重推机制进行事件去重，我好像没找到相应的代码

**Comment by mazhe-nerd** [comment]
> 我好像搜不到该群，顺便再问一个问题，该sdk似乎没有对飞书的重推机制进行事件去重，我好像没找到相应的代码

可以飞书找下我哈：mazhe.nerd

**Comment by mazhe-nerd** [comment]
在特定的框架，可以写不同的适配器来支持，可以参考：https://github.com/larksuite/node-sdk/blob/main/README.zh.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%80%82%E9%85%8D%E5%99%A8
