### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by 97Hanayo** [larksuite/node-sdk#80]
Koa部分的引用名写反了！
![QQ截图20240403185913](https://github.com/larksuite/node-sdk/assets/28947953/56bebbc6-5c33-4097-bc5d-20be4fbe3684)
![QQ截图20240403185852](https://github.com/larksuite/node-sdk/assets/28947953/d7c25867-89a9-4fc9-94d9-fc7d0ee5d3b1)

**Comment by mazhe-nerd** [comment]
感谢同学反馈，已修复
