### ISSUE TITLE
yarn.lock 中包含字节内网registry地址

### ISSUE THREAD

**Issue by yunnysunny** [larksuite/node-sdk#84]
想clone项目手动修改其中代码，结果发现yarn install 的时候报错，看了一下yarn.lock 中包含bnpm.byted.org，导致开发者无法手动运行yarn install 。
已经提交pull request https://github.com/larksuite/node-sdk/pull/83

**Comment by mazhe-nerd** [comment]
fixed: https://github.com/larksuite/node-sdk/pull/85
