### ISSUE TITLE
drive.file.bitable_record_changed_v1 缺失

### ISSUE THREAD

**Issue by 0jinxing** [larksuite/node-sdk#87]
## 文档里面也不全
<img width="896" alt="截屏2024-05-10 11 34 05" src="https://github.com/larksuite/node-sdk/assets/32119282/14c6f8f5-f511-4cbc-995d-872cc6aad928">

## `code-gen/events-template.ts` 里面缺失了 drive.file.bitable_record_changed_v1 👇
<img width="1167" alt="截屏2024-05-10 11 34 31" src="https://github.com/larksuite/node-sdk/assets/32119282/aa5b8248-e2f2-4d84-b594-fa1701b1ae7a">

**Comment by 0jinxing** [comment]
我现在非常生气🐶，建议中午 加班 补上[狗头保命]

**Comment by mazhe-nerd** [comment]
抱歉同学。有一些事件的定义由于数据格式的问题没法解析自动生成，所以现阶段需要手动来声明一下，不影响使用，参考这个issue：https://github.com/larksuite/node-sdk/issues/64。

下个版本会加上自定义event的范型声明，这样就可以扩展code-gen里不存在的event类型了。
对于没法生成的我们在推动数据结构适配，这期间只能手动声明下哈。

**Comment by 0jinxing** [comment]
我还有一个 疑问 🤔
`drive.file.bitable_record_changed_v1` 我怎么可以拿到 event.after_value 的类型文档

主要 field_value 里面 JSON.parse 之后的
```
[
  {
    "field_id": "fldoveTtfM",
    "field_value": "[{\"text\":\"管三水生\",\"type\":\"text\"}]"
  },
  {
    "field_id": "fldiYHPR8f",
    "field_value": ""
  },
  {
    "field_id": "fldJ3nwXOH",
    "field_value": "optK9Y3D7F"
  },
  {
    "field_id": "flddexuKKw",
    "field_value": "[{\"type\":\"url\",\"text\":\"下游节点确认调度策略会使得excel表导入的时候重跑下游任务失去关联\",\"link\":\"http://下游节点确认调度策略会使得excel表导入的时候重跑下游任务失去关联\",\"csvText\":\"http://下游节点确认调度策略会使得excel表导入的时候重跑下游任务失去关联\"}]"
  }
]
```

**Comment by 0jinxing** [comment]
@mazhe-nerd 我没翻到 对应的 文档，sdk 里面也没找到 😭

**Comment by 0jinxing** [comment]
https://open.feishu.cn/document/server-docs/docs/bitable-v1/bitable-structure#%E9%99%84%E4%BB%B6

我找到文档了，要是 sdk 里面有 types 定义就更好了 🍖🍖
