### ISSUE TITLE
批量获取用户信息接口中应该如何填写多个userId

### ISSUE THREAD

**Issue by FinaLone** [larksuite/node-sdk#88]
接口文档：
https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/contact-v3/user/batch

我试用了user_ids直接传数组，是不行的。最终传递的格式如下：
<img width="1363" alt="image" src="https://github.com/larksuite/node-sdk/assets/10736163/073be2d0-1a20-407d-bb39-c22eb357063c">

参考axios加了 `qs.stringify(params, { arrayFormat: 'repeat' })` 也没有用

**Comment by mazhe-nerd** [comment]
目前解决方案是手动调用sdk的request方法，然后用paramsSerializer把参数拍平，像这样：https://stackoverflow.com/questions/49944387/how-to-correctly-use-axios-params-with-arrays

**Comment by FinaLone** [comment]
> 目前解决方案是手动调用sdk的request方法，然后用paramsSerializer把参数拍平，像这样：https://stackoverflow.com/questions/49944387/how-to-correctly-use-axios-params-with-arrays

好的， 我是直接用axios调了

**Comment by xinxiafeng** [comment]
这个问题大概什么时候解决，我也遇到了。

还有就是ts定义有点问题
![image](https://github.com/larksuite/node-sdk/assets/29367267/8ab30cc8-d4bb-414b-bfc2-5ae218ec7fe7)
应该是个string[]的怎么还定义成number了

**Comment by mazhe-nerd** [comment]
先用上面的方式解决哈，ts类型可以先ignore一下

**Comment by mazhe-nerd** [comment]
升级到1.37.0可用
