### ISSUE TITLE
审批相关的事件推送

### ISSUE THREAD

**Issue by ayf19** [larksuite/node-sdk#9]
[审批相关的事件推送](https://open.feishu.cn/document/ukTMukTMukTM/ugDNyUjL4QjM14CO0ITN)目前还没有写定义，请问这部分支持是否有时间表？或者在 `lark.EventDispatcher` 中是否有自己写 sdk 中未定义的事件推送的方法？

**Comment by mazhe-nerd** [comment]
> [审批相关的事件推送](https://open.feishu.cn/document/ukTMukTMukTM/ugDNyUjL4QjM14CO0ITN)目前还没有写定义，请问这部分支持是否有时间表？或者在 `lark.EventDispatcher` 中是否有自己写 sdk 中未定义的事件推送的方法？

你好同学，如果在Dispatcher的register函数参数中没有提示出响应事件的名称，可以自己手动将事件的type作为key填入哈，这样事件的处理器就注册上了：
![image](https://user-images.githubusercontent.com/106217973/192228096-65ac223b-97bb-4d29-96c5-e4b3bee0e623.png)
![image](https://user-images.githubusercontent.com/106217973/192228728-5c24ab47-fbea-41d5-8dee-f7d59a7bfd6e.png)

事件和请求sdk中未定义的部分我们会陆续补充进来哈～

**Comment by ayf19** [comment]
> > [审批相关的事件推送](https://open.feishu.cn/document/ukTMukTMukTM/ugDNyUjL4QjM14CO0ITN)目前还没有写定义，请问这部分支持是否有时间表？或者在 `lark.EventDispatcher` 中是否有自己写 sdk 中未定义的事件推送的方法？
> 
> 你好同学，如果在Dispatcher的register函数参数中没有提示出响应事件的名称，可以自己手动将事件的type作为key填入哈，这样事件的处理器就注册上了： ![image](https://user-images.githubusercontent.com/106217973/192228096-65ac223b-97bb-4d29-96c5-e4b3bee0e623.png) ![image](https://user-images.githubusercontent.com/106217973/192228728-5c24ab47-fbea-41d5-8dee-f7d59a7bfd6e.png)
> 
> 事件和请求sdk中未定义的部分我们会陆续补充进来哈～

这个例子里的 `leave_approvalV2` 是已经定义过的，但是对于完全没有定义过的 `approval_task` 直接写会导致 TypeScript 会报错，这里只能手动添加 `@ts-ignore`，希望能早点完善事件推送的定义，或者在 `IHandlers` 里添加 `[event_type: string]: (data: any) => Promise<any> | any`。

**Comment by mazhe-nerd** [comment]
> 

好的同学，我记个todo，尽快加上～

**Comment by mazhe-nerd** [comment]
> > > [审批相关的事件推送](https://open.feishu.cn/document/ukTMukTMukTM/ugDNyUjL4QjM14CO0ITN)目前还没有写定义，请问这部分支持是否有时间表？或者在 `lark.EventDispatcher` 中是否有自己写 sdk 中未定义的事件推送的方法？
> > 
> > 
> > 你好同学，如果在Dispatcher的register函数参数中没有提示出响应事件的名称，可以自己手动将事件的type作为key填入哈，这样事件的处理器就注册上了： ![image](https://user-images.githubusercontent.com/106217973/192228096-65ac223b-97bb-4d29-96c5-e4b3bee0e623.png) ![image](https://user-images.githubusercontent.com/106217973/192228728-5c24ab47-fbea-41d5-8dee-f7d59a7bfd6e.png)
> > 事件和请求sdk中未定义的部分我们会陆续补充进来哈～
> 
> 这个例子里的 `leave_approvalV2` 是已经定义过的，但是对于完全没有定义过的 `approval_task` 直接写会导致 TypeScript 会报错，这里只能手动添加 `@ts-ignore`，希望能早点完善事件推送的定义，或者在 `IHandlers` 里添加 `[event_type: string]: (data: any) => Promise<any> | any`。

好的同学，我记个todo，尽快加上～

**Comment by mazhe-nerd** [comment]
v1版本的事件目前都无法生成定义，只能手动加上然后ts-ignore

**Comment by mazhe-nerd** [comment]
v1版本的事件目前都无法生成定义，只能手动使用然后ts-ignore
