### ISSUE TITLE
如何Cache写入到redis里？ 

### ISSUE THREAD

**Issue by cxc222** [larksuite/node-sdk#90]
如题，可以提供一些demo吗？

**Comment by mazhe-nerd** [comment]
可以参考default-cache的实现：https://github.com/larksuite/node-sdk/blob/main/utils/default-cache.ts。把里面存储的部分换成redis就好

**Comment by cxc222** [comment]
> 可以参考default-cache的实现：[https://github.com/larksuite/node-sdk/blob/main/utils/default-cache.ts。把里面存储的部分换成redis就好](https://github.com/larksuite/node-sdk/blob/main/utils/default-cache.ts%E3%80%82%E6%8A%8A%E9%87%8C%E9%9D%A2%E5%AD%98%E5%82%A8%E7%9A%84%E9%83%A8%E5%88%86%E6%8D%A2%E6%88%90redis%E5%B0%B1%E5%A5%BD)

感谢，已经搞定了
