### ISSUE TITLE
在cloudflare worker中使用出现兼容问题

### ISSUE THREAD

**Issue by JackDrogon** [larksuite/node-sdk#91]
(error) Error: AggregateError:
    TypeError: Cannot destructure property 'tenant_access_token' of '(intermediate value)' as it is undefined.
        at Generator.next (<anonymous>)

已配置了`node_compat = true`
这里通用的代码，本地用node跑就没问题

**Comment by mazhe-nerd** [comment]
抓包看一下这个请求的返回值：`/open-apis/auth/v3/tenant_access_token/internal`，看错误是这个请求出问题了

**Comment by JackDrogon** [comment]
> 抓包看一下这个请求的返回值：`/open-apis/auth/v3/tenant_access_token/internal`，看错误是这个请求出问题了

还是之前有人提到过的axio在cloudflare默认使用fetch的问题，这个你们添加一下文档说明吧

**Comment by mazhe-nerd** [comment]
Duplicate of #51
