### ISSUE TITLE
使用createByCard无法直接调用卡片

### ISSUE THREAD

**Issue by xyhcode** [larksuite/node-sdk#94]
```
data: {
      code: 230099,
      msg: 'Failed to create card content.',
      error: { log_id: '2024070418495694C3C1B5391B73A7B448' }
    }
```
API控制台请求可以
<img width="864" alt="image" src="https://github.com/larksuite/node-sdk/assets/64968400/c7773cfa-8829-45f0-a0ca-47db57f0431a">

**Comment by mazhe-nerd** [comment]
和调试台等效的话，可以使用create；createByCard是语法糖，参数有差异。

**Comment by xyhcode** [comment]
> 和调试台等效的话，可以使用create；createByCard是语法糖，参数有差异。

<img width="416" alt="image" src="https://github.com/larksuite/node-sdk/assets/64968400/2f2cb572-bc50-4aa5-8b73-20d0471b5c0c">
对啊 我一样的传递 上面代码就这个没有传
```
template_variable: {
      content: "Card Content",
      title: "Card Title"
    }
```

**Comment by mazhe-nerd** [comment]
解决了嘛？看了下报错，原因是这个消息卡片似乎没有开权限给你的应用

**Comment by xyhcode** [comment]
> 解决了嘛？看了下报错，原因是这个消息卡片似乎没有开权限给你的应用

应该不是权限的问题 我开了全部权限
<img width="788" alt="image" src="https://github.com/larksuite/node-sdk/assets/64968400/3e5b1c57-4cd3-4b2c-a51a-8302e79b45b1">

**Comment by mazhe-nerd** [comment]
createByCard里的template_id是模版卡片的，需要在卡片搭建工具这里给你的这个应用开权限：
![img_v3_02cf_470cd4fe-af45-44c7-b684-b279dfaafdag](https://github.com/larksuite/node-sdk/assets/106217973/22543f8e-56e2-48bd-ae59-b398ef3aba3b)

**Comment by xyhcode** [comment]
> createByCard里的template_id是模版卡片的，需要在卡片搭建工具这里给你的这个应用开权限： ![img_v3_02cf_470cd4fe-af45-44c7-b684-b279dfaafdag](https://private-user-images.githubusercontent.com/106217973/345821813-22543f8e-56e2-48bd-ae59-b398ef3aba3b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTQ1ODgsIm5iZiI6MTcyMDA5NDI4OCwicGF0aCI6Ii8xMDYyMTc5NzMvMzQ1ODIxODEzLTIyNTQzZjhlLTU2ZTItNDhiZC1hZTU5LWIzOThlZjNhYmEzYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQxMTU4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NWE1MjI2NzYzNjUwYTY1NWMyMDhlZWExMTAwZTdkNGFhY2I1NWVjZmQ5YjllNmUzZDhhN2MwMDc5MmZlODM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ywnGEHb7bpfkuOH9GM2XPJxur7yLdPPq4B44vuA2yCo)

<img width="369" alt="image" src="https://github.com/larksuite/node-sdk/assets/64968400/f87d0742-e87f-4d46-9f29-c26b12db60e8">
对 我也开了 不知道为什么 我下午测试的用API控制台 明明测试返回成功 但是看消息就是没有

**Comment by mazhe-nerd** [comment]
调试台的appid和代码里的是同一个嘛？

**Comment by xyhcode** [comment]
> 调试台的appid和代码里的是同一个嘛？

一样的
