### ISSUE TITLE
client.im.file.create上传类型为stream时报错

### ISSUE THREAD

**Issue by ifuner** [larksuite/node-sdk#96]
![image](https://github.com/user-attachments/assets/f0bbe3a5-b375-4201-81a7-1103cab9f003)

**Comment by ifuner** [comment]
`
  const result = await client.im.file.create({
      data: {
       file_type: 'stream',
      file: fs.readFileSync(path.join(process.cwd(), 'package.json')),
      file_name: 'package.json ',
      }
    });
`

**Comment by ifuner** [comment]
```javascript

  const result = await client.im.file.create({
      data: {
       file_type: 'stream',
      file: fs.readFileSync(path.join(process.cwd(), 'package.json')),
      file_name: 'package.json ',
      }
    });
```

**Comment by mazhe-nerd** [comment]
Duplicate of: https://github.com/larksuite/node-sdk/issues/39
